### ISSUE TITLE
Error on scroll button position

### ISSUE THREAD

**Issue by enniolopes** [TriangulosTecnologia/lps#11]
The scroll button breaks on pages.

<hr>

![image](https://user-images.githubusercontent.com/15162145/127011367-60743dd3-e3b6-4905-b9d9-4d006d6537c1.png)

![image](https://user-images.githubusercontent.com/15162145/127011380-fe8bee8d-79ac-4306-aaee-76de9da2a0aa.png)

![image](https://user-images.githubusercontent.com/15162145/127011399-5a544985-e44e-4c0a-be25-5ad06a7586bc.png)

**Comment by arantespp** [comment]
I need a minimal height to properly configure the pages to avoid overflow.

**Comment by enniolopes** [comment]
> 
> 
> I need a minimum height to configure the pages to avoid overflow properly.

Is possible to use min-height: 100vh?

Otherwise, I think the minimum is 632px

**Comment by arantespp** [comment]
@RayzaOliveira could you handle this issue? I think we can solve this problem using flexbox. We can create a div with column direction and justify content space-evenly. What do you think?

**Comment by RayzaOliveira** [comment]
> @RayzaOliveira could you handle this issue? I think we can solve this problem using flexbox. We can create a div with column direction, height 100%, and justify content space-evenly. What do you think?

It's an excellent option, I'll adjust it then.
