### ISSUE TITLE
Last page footer position and size

### ISSUE THREAD

**Issue by enniolopes** [TriangulosTecnologia/lps#12]
- [ ] Privacy terms font-size to ~10px
- [ ] ~~Use all width available space to Privacy terms paragraph~~
- [ ] Footer position at footer (at bottom of page)

<hr>

![image](https://user-images.githubusercontent.com/15162145/127013765-b5552efe-9408-4f64-8956-03703bebdd6a.png)

**Comment by arantespp** [comment]
For large screens, full width is bad for user experience, even more with the small font size. Keep with this? [Reference.](https://baymard.com/blog/line-length-readability)

**Comment by enniolopes** [comment]
> 
> 
> For large screens, full width is bad for user experience, even more with the small font size. Keep with this? [Reference.](https://baymard.com/blog/line-length-readability)

ok, I remove the width task
