### ISSUE TITLE
Set the scroll component and logo fixed

### ISSUE THREAD

**Issue by enniolopes** [TriangulosTecnologia/lps#14]
Could we set the scroll component and logo fixed on screen? It means that the components will not scroll, it will be fixed on pages scroll.

<hr>

![image](https://user-images.githubusercontent.com/15162145/127040003-921e1f98-2fd8-46e2-b9df-dc16aeaf7bd0.png)

**Comment by arantespp** [comment]
Is this issue a question or an enhancement? I don't know if it's possible because of Fullpage.js. We need to do some tests before answering. @RayzaOliveira, do you know?

**Comment by RayzaOliveira** [comment]
> Is this issue a question or an enhancement? I don't know if it's possible because of Fullpage.js. We need to do some tests before answering. @RayzaOliveira, do you know?

I'm going to run some tests on this to see what we can do
