### ISSUE TITLE
Document monorepo and Simulare landing page

### ISSUE THREAD

**Issue by arantespp** [TriangulosTecnologia/lps#8]
### Description

We can add the following information to README.

#### Monorepo

- [x] Write a little about the project
- [x] Put the libraries we'll use (Next.js, Fullpage.js, ThemeUI, RHF, Yup, React.js...)
- [x] Design pattern

#### Simulare

- [x] Write about Simulare
- [x] Write about the CRM we chose.

**Comment by enniolopes** [comment]
@arantespp could you attach the link to the readme file in this issue, please?

**Comment by enniolopes** [comment]
[Monday + Simulare]
A Simulare nasceu com o propósito p descomplicar o modo de venda a partir da geração de propostas para Terreno + Construção com informações em tempo real vindo da instituição financeira Caixa Econômica Federal, bem como também trazer mais confiança, velocidade e o melhor negócio. O core da solução é a produção, com acurácia e rapidez, de propostas para viabilizar o financiamento da construção da casa própria.

The Simulare solution was born with the purporse to facilitate the salles, creating land + construction deals with Caixa Econômica Federal on time finaces informations. That is the way  Simulares solution brings more trust, speed and deals that fits in your custumer profile. The solution core is the production, with speed and accuracy, of proposal to make viable the financign of the own house construction.


Monday
Monday.com Ltd. is a Cloud-based platform that allows companies to create their own applications and work management software. The tool have a many aplications, we can management marketing campaing, projetcs flow, sells pipeline and more. Monday is a system usefull to one or more department, that is why we chose work with them. We can make monday a hub to all Simulare projects, to including all department in just one enviroment.

**Comment by RayzaOliveira** [comment]
> @arantespp could you attach the link to the readme file in this issue, please?

follow the readme link -> https://github.com/TriangulosTecnologia/lps/blob/8-document-monorepo-and-simulare-landing-page/README.md
